development:
  secret_key_base: 1f9f3e703647bf39e98162b1d4dc8cd67d51cbe1f95153b7147219d1b944f07503f6c0ad3b027492be3fc792875fa523f671abae209da272018d8bd0fd68cf24
  rakuten_application_id: <%= ENV["RAKUTEN_APPLICATION_ID"] %>
  rakuten_affiliate_id: <%= ENV["RAKUTEN_AFFILIATE_ID"] %>

test:
  secret_key_base: c4cc3783df352ea33aa999af6319f04948b8dc06b51045edc990024a379dcbd8f55d91ab17c09de39c29efbfabdd120d01259777f72173aac417fa6a427faba1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rakuten_application_id: <%= ENV["RAKUTEN_APPLICATION_ID"] %>
  rakuten_affiliate_id: <%= ENV["RAKUTEN_AFFILIATE_ID"] %>